---
- name: Update all packages on Debian and Red Hat systems
  hosts: all
  become: true
  tasks:

    - name: Update package cache and upgrade on Debian-based systems
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update all packages on Red Hat-based systems
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
